
const SUPABASE_URL = "https://hhdbupqwqlkkbaduxzgt.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9........";


const S={leads:'ll_blue_leads',refs:'ll_blue_refs',partners:'ll_blue_partners',firms:'ll_blue_firms'};
function get(k){return JSON.parse(localStorage.getItem(k)||'[]')}
function set(k,v){localStorage.setItem(k,JSON.stringify(v))}
function makeId(p){return p+'-'+String(Date.now()).slice(-6)}
function val(id){return document.getElementById(id)?.value}
function init(){if(get(S.firms).length===0){set(S.firms,[{id:'FIRM-001',name:'Demo Injury Law Firm',email:'firmdemo@legalliftgroup.com',password:'firm123',status:'Active'}])}}
function checkCase(){let score=0;if(val('injured')==='Yes')score++;if(val('fault')==='No'||val('fault')==='Not Sure')score++;if(val('attorney')==='No')score++;if(val('treatment')!=='Not Yet')score++;let b=document.getElementById('caseResult');b.classList.remove('hidden');b.textContent=score>=3?'Strong review: this may qualify for LegalLift review.':score>=2?'Needs review: submit the full intake so LegalLift can review it.':'Limited review: more information may be needed.'}
function saveLead(e){e.preventDefault();let f=new FormData(e.target);let files=[...(document.getElementById('docs')?.files||[])].map(x=>x.name);let lead={id:makeId('LL'),created:new Date().toLocaleString(),status:'New Lead',firmStatus:'Unassigned',assignedFirm:'',firstName:f.get('firstName'),lastName:f.get('lastName'),phone:f.get('phone'),email:f.get('email'),cityState:f.get('cityState'),bestTime:f.get('bestTime'),accidentType:f.get('accidentType'),accidentDate:f.get('accidentDate'),injured:f.get('injured'),fault:f.get('fault'),police:f.get('police'),treatment:f.get('treatment'),attorney:f.get('attorney'),notes:f.get('notes'),uploads:files};let a=get(S.leads);a.unshift(lead);set(S.leads,a);document.getElementById('leadResult').classList.remove('hidden');document.getElementById('leadResult').textContent='Case submitted. Tracking ID: '+lead.id;e.target.reset()}
function saveReferral(e){e.preventDefault();let f=new FormData(e.target);let a=get(S.refs);a.unshift({id:makeId('REF'),created:new Date().toLocaleString(),status:'New Referral',name:f.get('name'),phone:f.get('phone'),accidentType:f.get('accidentType'),accidentDate:f.get('accidentDate'),cityState:f.get('cityState'),notes:f.get('notes')});set(S.refs,a);document.getElementById('referralResult').classList.remove('hidden');document.getElementById('referralResult').textContent='Referral submitted.';e.target.reset()}
function savePartner(e){e.preventDefault();let f=new FormData(e.target);let a=get(S.partners);a.unshift({id:makeId('P'),created:new Date().toLocaleString(),status:'New Partner',business:f.get('business'),contact:f.get('contact'),phone:f.get('phone'),email:f.get('email'),cityState:f.get('cityState'),tier:f.get('tier'),type:f.get('type')});set(S.partners,a);document.getElementById('partnerResult').classList.remove('hidden');document.getElementById('partnerResult').textContent='Partner request submitted.';e.target.reset()}
function adminLogin(){if(val('adminPass')!=='legallift'){alert('Admin password: legallift');return}document.getElementById('adminLogin').classList.add('hidden');document.getElementById('adminPanel').classList.remove('hidden');renderAdmin()}
function addFirm(e){e.preventDefault();let f=new FormData(e.target);let a=get(S.firms);a.unshift({id:makeId('FIRM'),name:f.get('name'),email:f.get('email'),password:f.get('password')||'firm123',status:'Active'});set(S.firms,a);e.target.reset();renderAdmin()}
function setLead(id,key,value){let a=get(S.leads).map(l=>l.id===id?{...l,[key]:value,status:key==='assignedFirm'&&value?'Sent to Firm':key==='status'?value:l.status,firmStatus:key==='assignedFirm'&&value?'Pending Firm Review':l.firmStatus}:l);set(S.leads,a);renderAdmin()}
function renderAdmin(){init();let leads=get(S.leads),refs=get(S.refs),partners=get(S.partners),firms=get(S.firms);document.getElementById('metrics').innerHTML=`<div class=kpi><strong>${leads.length}</strong>Leads</div><div class=kpi><strong>${refs.length}</strong>Referrals</div><div class=kpi><strong>${partners.length}</strong>Partners</div><div class=kpi><strong>${firms.length}</strong>Law Firms</div>`;document.getElementById('leadList').innerHTML=leads.map(l=>`<div class=box><h3>${l.id} • ${l.firstName||''} ${l.lastName||''} <span class=badge>${l.status}</span></h3><p>${l.phone||''} • ${l.email||''} • ${l.cityState||''}</p><p>${l.accidentType||''} • Date: ${l.accidentDate||''} • Injured: ${l.injured||''} • Attorney: ${l.attorney||''}</p><p>Uploads: ${(l.uploads||[]).join(', ')||'None'}</p><label>Status<select onchange="setLead('${l.id}','status',this.value)">${['New Lead','Contacted','Verified','Sent to Firm','Accepted','Signed Case'].map(x=>`<option ${x===l.status?'selected':''}>${x}</option>`).join('')}</select></label><label>Assign To Law Firm<select onchange="setLead('${l.id}','assignedFirm',this.value)"><option value="">Unassigned</option>${firms.map(f=>`<option value="${f.id}" ${f.id===l.assignedFirm?'selected':''}>${f.name}</option>`).join('')}</select></label></div>`).join('')||'<p>No leads yet.</p>';document.getElementById('refList').innerHTML=refs.map(r=>`<div class=box><h3>${r.id} • ${r.name}</h3><p>${r.phone} • ${r.accidentType} • ${r.status}</p></div>`).join('')||'<p>No referrals yet.</p>';document.getElementById('partnerList').innerHTML=partners.map(p=>`<div class=box><h3>${p.id} • ${p.business}</h3><p>${p.tier} • ${p.type} • ${p.phone}</p></div>`).join('')||'<p>No partners yet.</p>';document.getElementById('firmList').innerHTML=firms.map(f=>`<div class=box><h3>${f.id} • ${f.name}</h3><p>${f.email} • ${f.status}</p></div>`).join('')}
function firmLogin(){init();let firm=get(S.firms).find(f=>f.email===val('firmEmail')&&f.password===val('firmPassword'));if(!firm){alert('Demo firm login: firmdemo@legalliftgroup.com / firm123');return}localStorage.setItem('currentFirm',firm.id);document.getElementById('firmLogin').classList.add('hidden');document.getElementById('firmPanel').classList.remove('hidden');document.getElementById('firmName').textContent=firm.name;renderFirm()}
function firmDecision(id,value){let a=get(S.leads).map(l=>l.id===id?{...l,firmStatus:value,status:value==='Accepted'?'Accepted':value==='Signed Case'?'Signed Case':l.status}:l);set(S.leads,a);renderFirm()}
function renderFirm(){let fid=localStorage.getItem('currentFirm');let leads=get(S.leads).filter(l=>l.assignedFirm===fid);document.getElementById('firmLeads').innerHTML=leads.map(l=>`<div class=box><h3>${l.id} • ${l.firstName} ${l.lastName}</h3><p>${l.phone} • ${l.email} • ${l.cityState}</p><p>${l.accidentType} • Injured: ${l.injured} • Police: ${l.police}</p><p>${l.notes||''}</p><label>Decision<select onchange="firmDecision('${l.id}',this.value)"><option>Pending Firm Review</option><option>Accepted</option><option>Rejected</option><option>Need More Info</option><option>Signed Case</option></select></label></div>`).join('')||'<p>No assigned leads yet. Assign a lead from the Admin Dashboard first.</p>'}
document.addEventListener('DOMContentLoaded',init)
